version: "3.8"

services:
  # 1. Main full-stack node service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: harnexis_web_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_secure_pass@postgres_db:5432/harnexis_db?schema=public
      - REDIS_URL=redis://redis_queue:6379
      - JWT_ACCESS_SECRET=co-engine-access-secret-3342
      - JWT_REFRESH_SECRET=co-engine-refresh-secret-9912
      - NODE_ENV=production
    depends_on:
      - postgres_db
      - redis_queue
    restart: always

  # 2. Relational Postgres Database instance
  postgres_db:
    image: postgres:15-alpine
    container_name: harnexis_postgres_node
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_secure_pass
      - POSTGRES_DB=harnexis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 3. Redis Queue cache element
  redis_queue:
    image: redis:7-alpine
    container_name: harnexis_redis_node
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
